[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Disable secrets scanning for expected environment variables
  SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_URL,VITE_SUPABASE_ANON_KEY,VITE_SUPABASE_SERVICE_ROLE_KEY,SUPABASE_SERVICE_ROLE_KEY"
  # Omit scripts directory from scanning as it contains development tools
  SECRETS_SCAN_OMIT_PATHS = "scripts/**"