[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Disable secrets scanning for expected environment variables
  SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_URL,VITE_SUPABASE_ANON_KEY,VITE_SUPABASE_SERVICE_ROLE_KEY,SUPABASE_SERVICE_ROLE_KEY"
  # Omit scripts directory from scanning as it contains development tools
  SECRETS_SCAN_OMIT_PATHS = "scripts/**"

# Enable compression
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache control for static assets
    Cache-Control = '''
    public,
    max-age=31536000,
    immutable'''

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# HTTP/2 Server Push
[[headers]]
  for = "/"
  [headers.values]
    Link = '''
    </assets/index-*.css>; rel=preload; as=style,
    </assets/index-*.js>; rel=preload; as=script,
    </assets/vendor-react-*.js>; rel=preload; as=script'''

# Redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Enable asset optimization
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true