-- Insert opponent teams data
INSERT INTO opponent_teams (
  team_name,
  short_name,
  rink_name,
  address,
  city,
  state,
  website,
  email,
  phone,
  facebook,
  head_coach,
  assistant_coaches,
  manager,
  president,
  founder,
  founded_year,
  age_range,
  program_type,
  notes,
  is_free_program,
  sponsor,
  primary_color,
  secondary_color
) VALUES 
(
  'Wings of Steel',
  'Wings',
  'Flyers Skate Zone',
  NULL,
  'Voorhees',
  'NJ',
  'wingsofsteel.org',
  NULL,
  NULL,
  '@wingsofsteel',
  'Paul Valentine',
  NULL,
  'Lori Kile (Brake)',
  NULL,
  'Tom Brake',
  2001,
  '5-18',
  'youth',
  'Youth team ages 5-18, FREE program, Founded 2001',
  true,
  NULL,
  '#1E3A8A', -- steel blue
  '#DC2626'  -- red
),
(
  'Hammerheads',
  'Hammerheads',
  'Northeast Skate Zone',
  '10990 Decatur Rd',
  'Philadelphia',
  'PA',
  NULL,
  'info@hammerheads.hockey',
  NULL,
  NULL,
  'Athan Blaine',
  ARRAY['Brian Olsen'],
  NULL,
  'Brian Olsen',
  NULL,
  NULL,
  NULL,
  'full',
  'Full program with adult & junior teams. Head Coach (Junior): Brian Olsen',
  false,
  NULL,
  '#1F2937', -- dark gray
  '#10B981'  -- green
),
(
  'DC Sled Sharks',
  'Sled Sharks',
  'MedStar Capitals Iceplex',
  '627 N. Glebe Rd Suite 800',
  'Arlington',
  'VA',
  NULL,
  'sledsharks@medstarnrh.org',
  '(571) 224-0555',
  NULL,
  'Tom Wallace',
  ARRAY['Sean Carlson'],
  NULL,
  NULL,
  NULL,
  NULL,
  '4-18',
  'youth',
  'Ages 4-18, MedStar NRH sponsored',
  false,
  'MedStar NRH',
  '#C8102E', -- capitals red
  '#002B5C'  -- capitals blue
),
(
  'Bennett Blazers',
  'Blazers',
  'Ice World',
  '1300 Governors Ct',
  'Abingdon',
  'MD',
  'iceworld.com',
  NULL,
  NULL,
  NULL,
  'Billy Zinkhan',
  ARRAY['Noah Grove'],
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'youth',
  'Part of Kennedy Krieger Institute. Asst Coach Noah Grove is a Paralympian',
  false,
  'Kennedy Krieger Institute',
  '#FF6F00', -- orange
  '#1E3A8A'  -- blue
),
(
  'Vineland Sled Stars',
  'Sled Stars',
  'Vineland Ice Arena',
  NULL,
  'Vineland',
  'NJ',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  2002,
  NULL,
  'youth',
  'Founded 2002. Moved from Vineland (original team location)',
  false,
  NULL,
  '#FBBF24', -- yellow
  '#1E3A8A'  -- blue
),
(
  'Woodbridge Warriors',
  'Warriors',
  'Woodbridge Community Center',
  NULL,
  'Woodbridge',
  'NJ',
  'warriorssledhockey.org',
  NULL,
  '(732) 586-0520',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'full',
  'Also has special hockey program',
  false,
  NULL,
  '#7C3AED', -- purple
  '#DC2626'  -- red
),
(
  'Sled Stars',
  'Sled Stars',
  'Hollydell Ice Arena',
  '601 Holly Dell Dr',
  'Sewell',
  'NJ',
  'hollydell.com',
  'info@hollydell.com',
  '(856) 589-5599',
  NULL,
  'Brian Olsen',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'youth',
  'Coach from Williamstown. Sponsored by Weisman''s Children''s Hospital',
  false,
  'Weisman''s Children''s Hospital',
  '#059669', -- teal
  '#F59E0B'  -- amber
),
(
  'Pittsburgh Mighty Penguins',
  'Mighty Penguins',
  'UPMC Lemieux Sports Complex',
  NULL,
  'Pittsburgh',
  'PA',
  'penguinssledhockey.org',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  1998,
  NULL,
  'full',
  'Founded 1998. Multiple teams: Youth Novice, Junior, Adult',
  false,
  'UPMC',
  '#FCB514', -- penguins gold
  '#000000'  -- black
);